:development
  :adapter => "mysql",
  :host => "localhost",
  :username => "root",
  :password => "password",
  :database => "some_database"  

:test
  :adapter => "mysql",
  :host => "localhost",
  :username => "root",
  :password => "password",
  :database => "some_database"
  
:production
  :adapter => "mysql",
  :host => "localhost",
  :username => "root",
  :password => "password",
  :database => "some_database"  